---
title: "Motivation"
author: "Suyoung Park (spark148)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE,message=FALSE}
library(readxl)
library(glmdr)
library(brglm2)
library(arm)
library(ggplot2)
```


# Motivation

## Agresti Complete Separation Example


```{r}
x <- c(10,20,30,40,60,70,80,90,65)
y <- c(0,0,0,0,1,1,1,1,0)
glm(y~x,family="binomial")
plot(y~x, pch=16)


x <- c(10,20,30,40,60,70,80,90)
y <- c(0,0,0,0,1,1,1,1)
lst <- rep(NA,100)
for(i in 1:100){
  lst[i] <- suppressWarnings(logLik(glm(y~x, family="binomial", control = list(maxit=i,eps=1e-50))))
}
plot(lst,ylab="Log Likelihood",xlab="i-th iteration",type="l")
```


## Data Cleaning

```{r}
dat <- readxl::read_xlsx("../Corn_data/Combined_Final_Product.xlsx")
names(dat)[c(10,8)] <- c("Kernel.color","Pop.structure")
dat$Pop.structure <- factor(dat$Pop.structure)
Xind <- 11:ncol(dat)
```

## Univariate Case

When we fit the logstic model one by one (univariate case), there is no separation.

```{r}
#10 = Kenerl color, 8 = Pop structure, Xind = Markers
foo <- dat[, c(10,8,Xind)] 
n <- ncol(foo)
ret_vec <- rep(TRUE,n) #TRUE: separation does not exist | FALSE: spearation exists
Y <- foo$Kernel.color
for(i in 2:n){
  X <- unlist(foo[,i])
  mod <- glmdr(Y ~ X, family="binomial")
  ret_vec[(i-1)] <- is.null(mod$linearity)
}
all(ret_vec)
```

```{r}
#10 = Kenerl color, 8 = Pop structure, Xind = Markers
foo <- as.data.frame(dat[, c(10,8,Xind)] )
n <- ncol(foo)
ret_vec <- rep(TRUE,(n-1)) #TRUE: separation does not exist | FALSE: spearation exists
Y <- foo$Kernel.color
for(i in 4:n){
  cur_dat <- data.frame(Y,foo[,i-1],foo[,i],foo[,i-2])
  mod <- glmdr(Y ~ ., data=cur_dat,family="binomial")
  ret_vec[(i-2)] <- is.null(mod$linearity)
}

i<-3
cur_dat <- data.frame(Y,foo[,10:12])
mod <- glmdr(Y ~ ., data=cur_dat, family="binomial")

all(ret_vec)
```


## Multivariate Case

```{r}
#10 = Kenerl color, 8 = Pop structure, Xind = Markers, (15,19,22,23,24) = multi-collinearity
foo <- as.data.frame(dat[, c(10,8,Xind[-c(15,19,22,23,24)])])
foo$Kernel.color <- as.numeric(foo$Kernel.color)
mod <- glm(Kernel.color ~., data=foo, family=binomial(link="logit"))
mod1 <- glmdr(Kernel.color ~., data=foo, family="binomial")
mod2 <- bayesglm(Kernel.color ~., data=foo, family=binomial(link="logit"))

sub_foo <- as.data.frame(cbind(foo$Kernel,scale(foo[,3:ncol(foo)])))

tmp_mod <- glmdr(V1 ~., data=sub_foo, family="binomial")


test <- sub_foo[!(duplicated(sub_foo) | duplicated(sub_foo, fromLast = TRUE)), ]

unique()

with(foo,plot(S6_82170011,S6_82170814))

with(problematic_pts,plot(S6_82170011,S6_82170814,type="n"))
point()

ggplot(foo[!mod1$linearity,],aes(x=S6_82243856,y=S6_82218219))+
  geom_point(aes(color=Pop.structure,shape=as.factor(Kernel.color)),size=8)

 [1] "Kernel.color"  "Pop.structure" "S6_82170011"   "S6_82170814"   "S6_82170859"   "S6_82170897"   "S6_82170900"   "S6_82170957"  
 [9] "S6_82171038"   "S6_82174349"   "S6_82174376"   "S6_82174378"   "S6_82176123"   "S6_82185767"   "S6_82185973"   "S6_82186654"  
[17] "S6_82217770"   "S6_82217918"   "S6_82218018"   "S6_82218219"   "S6_82243856"  

S6_82170011
S6_82243856
S6_82218219
S6_82185973

mod2_coef <- coef(mod2)
tmp1 <- mod2_coef[-24] / mod2_coef[24]
ret <- model.matrix(mod2)[,-24] %*% tmp1

plot(foo[,21],foo[,20])

problematic_pts <- foo[!mod1$linearity,]
mod1.1 <- glmdr(Kernel.color ~., data=problematic_pts, family="binomial")
non_problematic_pts <- foo[mod1$linearity,]
mod1.2 <- glmdr(Kernel.color ~., data=non_problematic_pts, family="binomial")


plot(foo$Kernel.color, as.numeric(foo$Pop.structure=="tropical"))

mod3 <- logistf(Kernel.color ~., data=foo, family=binomial(link="logit"))

endometrial


with(endometrial,plot(NV,HG))

tmp_mod <- glmdr(HG~., data=endometrial,family="binomial")
tmp_coef <- coef(tmp_mod$om)

mod.mat <- model.matrix(tmp_mod$om)[,-2]

incpt <- (mod.mat[,c(1,2)] %*% tmp_coef[-c(2,4)]) / -tmp_coef[2]
slpt <- (tmp_coef[4]  %*% mod.mat[,c(3)] ) / -tmp_coef[2]
ret_vec <- model.matrix(tmp_mod$om)[,2] >= (c(incpt) + c(slpt))
ret_vec <- as.numeric(ret_vec)

plot((c(incpt) + c(slpt)),ret_vec)


plot((c(incpt) + c(slpt)),endometrial$NV)

idx <- (model.matrix(tmp_mod$om)[,-2] %*% tmp1) >= endometrial$NV


spe =   -tmp_coef[3] / tmp_coef[2]

plot(endometrial$PI,endometrial$NV)
abline(a=incpt,b=spe)


with(endometrial,which(HG==1 & NV == 1))

tmp_prob_pts <- endometrial[!tmp_mod$linearity,]
with(tmp_prob_pts,plot(NV,HG))

tmp_nprob_pts <- endometrial[tmp_mod$linearity,]
with(tmp_nprob_pts,plot(NV,HG))

with(endometrial,plot(NV,HG))
with(tmp_prob_pts,plot(NV,HG))
with(tmp_nprob_pts,plot(NV,HG))
```








```{r}
end_mod_glmdr <- glmdr(HG~.,data=endometrial,famil="binomial")
dat <- endometrial[,c(1),drop=FALSE]
df1 <- dat[endometrial$HG==0,,drop=FALSE]
df2 <- dat[endometrial$HG==1,,drop=FALSE]
endometrial
```





<!--
Poisson, real-world example when MLE not exist.
## Health Concerns of Teenagers

```{r}
Health <- expand.grid(concerns = c("sex","menstrual","healthy","nothing"),
                      age=c("12-15","16-17"),
                      gender=c("M","F"))
Health$Freq <- c(4,0,42,57,2,0,7,20,9,4,19,71,7,8,10,21)
mod_glmdr <- glmdr(Freq~concerns*age*gender,data=Health,family="poisson")
summary(mod_glmdr$om)
Health[!mod_glmdr$linearity,]
inf_glmdr <- inference(mod_glmdr)


```
-->